ashaki/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create')
]

shop/urls.py
from django.conf.urls import url
from . import views

app_name = 'shop'

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models
from shop.models import Product


class Order(models.Model):
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    email = models.EmailField()
    address = models.CharField(max_length=150)
    location = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

reservation/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 106)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'location']

reservation/forms.py
from django import forms

class ReservationForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    occation = forms.S

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)  # create a new cart object passing it the request object 
    product = get_object_or_404(Product, id=product_id) 
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item['product'],
                    price=item['price'],
                    quantity=item['quantity']
                )
            cart.clear()
        return render(request, 'orders/order/created.html', {'order': order})
    else:
        form = OrderCreateForm()
    return render(request, 'orders/order/create.html', {'form': form})

reservation/views.py
from django.shortcuts import render

# Create your views here.

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products
    }
    return render(request, 'shop/product/list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(request, 'shop/product/detail.html', context)

cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
Shopping Cart
{% endblock %}


{% block content %}
<div class="container">
    <div class="row" style="margin-top: 6%">
        <div class="col-sm-12">
            <h2>Your Shopping Cart
                <span class="badge pull-right">
                    {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                    My Shopping Order:
                    <a href="{% url 'cart:cart_detail' %}" style="color: #ffffff">
                        {{ totail_items }} item {{ totail_items|pluralize }}, Kshs. {{ cart.get_total_price }}
                    </a>
                    {% else %}
                    Your cart is empty.
                    {% endif %}
                    {% endwith %}
                </span>
            </h2>
            <table class="table table-responsive  table-condensed">
                <thead style="background-color: #FE980F; color: #ffffff;">
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Remove</th>
                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cart %}
                    {% with product=item.product  %}
                    <tr>
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}"
                                    alt="product_image" style="height: 130px; width: auto">
                            </a>
                        </td>
                        <td>{{ product.name }}</td>
                        <td>
                            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                {% csrf_token %}
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.update }}
                                <input type="submit" value="Update" class="btn btn-info">
                            </form>
                        </td>
                        <td>
                            <a href="{% url 'cart:cart_remove' product.id %}" class="btn btn-danger">X</a>
                        </td>
                        <td>kshs. {{ item.price }}</td>
                        <td>kshs. {{ item.total_price }}</td>
                    </tr>
                    {% endwith %}
                    {% endfor %}
                    <tr style="background-color: #FE980F; color: #ffffff;">
                        <td><b>Total</b></td>
                        <td colspan="4"></td>
                        <td colspan="num"><b>kshs. {{ cart.get_total_price }}</b></td>
                    </tr>
                </tbody>
            </table>
            <p class="text-right">
                <a href="{% url 'shop:product_list' %}" class="btn "
                    style="background-color: #FE980F; color: #ffffff;">Continue Shopping</a>
                <a href="{% url 'orders:order_create' %}" class="btn btn-info">Checkout</a>
            </p>
        </div>
    </div>
</div>
{% endblock %}

orders/templates/orders/order/create.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
Your Shopping Cart| Checkout
{% endblock %}

{% block content %}
<div class="container">
    <div class="row" style="margin-top: 6%">
        <div class="col-md-8">
            <h4 class="page-header">Checkout</h4>
            <form action="." method="post">
                {% csrf_token %}
                {{ form.as_p }}<br>
                <input type="submit" class="btn" value="Submit order"
                    style="background-color:rgb(177, 35, 71); color: #ffffff;">
            </form>
        </div>
        <div class="col-md-4">
            <div class="page-header">
                Order Summary
            </div>
            <ul class="list-group">
                {% for item in cart %}
                <li class="list-group-item">
                    {{ item.quantity }}x {{ item.product.name }}
                    <span>Kshs. {{ item.total_price }}</span>
                </li>
                {% endfor %}

                <li class="list-group-item active"
                    style="background-color:rgb(177, 35, 71); color: #ffffff; border-radius: rgb(177, 35, 71); ">Total
                    Cost: kshs. {{ cart.get_total_price }}</li>
            </ul>

        </div>
    </div>
</div>
{% endblock %}

orders/templates/orders/order/created.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
Your Shopping Cart| Thank you
{% endblock %}

{% block content %}
<div class="container">
    <div class="row" style="margin-top: 6%">
        <div class="col-md-8 col-md-offset-2">
            <h3 class="page-header">Thank You For Shopping With Us
            </h3>
            <p>Your order has been successfully completed. Your order number is <strong>{{ order.id }}</strong>.</p>
        </div>
    </div>
</div>
{% endblock %}

reservation/templates/reservation/reservation.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
Reservation
{% endblock %}


{% block content %}
<div class="container">
    <div class="row">
        <form action="submit-checkout" method="post" class="form-horizontal">
            <div class="col-sm-4 col-sm-offset-1">
                <legend>Contact Info</legend>
                <ul class="contact-info">
                    <li>
                        <i class="icon-home"></i> P.O.Box 5655, <br>Harlinghum, Nairobi.
                    </li>
                    <li><i class="icon-phone"></i> (+254) 465-6789</li>
                    <li><i class="icon-envelope"></i>info@ashaki.co</li>
                    <li><i class="fas fa-envelope"></i>Email: <a href="mailto:ashaki@gmail.com">Ashaki@gmail.com</a></p>
                    </li>
                </ul>
            </div>
            <div class="col-sm-1">

            </div>
            <div class="col-sm-4">
                <div class="signup-form">
                    <!--sign up form-->
                    <legend>Reservation Form</legend>
                    <div class="form-group ">
                        <input type="text" class="form-control" name="name" id="name" value="" placeholder="Your Name">
                        <span class="text-danger"></span>
                    </div>
                    <div class="form-group ">
                        <input type="text" class="form-control" value="" name="email" id="email"
                            placeholder="Your E-mail">
                        <span class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <select class="form-control" id="occation">
                            <option>Select an Occation</option>
                            <option>Wedding Ceremony</option>
                            <option>Birthday</option>
                            <option>Others</option>
                        </select>
                    </div>
                    <div class="form-group ">
                        <input type="text" class="form-control" name="pincode" value="" id="date"
                            placeholder="Date &amp; Time">
                        <span class="text-danger"></span>
                    </div>
                    <div class="form-group ">
                        <textarea name="" id="message" cols="30" rows="5" class="form-control"
                            placeholder="Message"></textarea>
                        <span class="text-danger"></span>
                    </div>
                    <input class="btn btn-outline-warning" value="Send Message" type="submit">
                </div>
                <!--/sign up form-->
            </div>
        </form>
    </div>
</div>
{% endblock %}

shop/templates/shop/product/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row" style="margin-top: 6%">

        <div class="col-sm-8 blog-main">

            <div class="blog-post">
                <div class="row">
                    <div class="card">
                        <div class="card-body">
                            <div class="col-md-6 text-right">
                                <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}"
                                    alt="product_image" style="height: 170px; width: auto">
                            </div>
                            <div class="col-md-6" style="padding-left: 20px">
                                <h3>{{ product.name }}</h3>
                                <h6><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h6>
                                <p class="text-muted">Kshs. {{ product.price }}</p>
                                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ cart_product_form }}
                                    <input type="submit" value="place order" class="btn "
                                        style="background-color:#FE980F; color: #ffff;">
                                </form>
                                <p>{{ product.description|safe|linebreaksbr }}</p>
                            </div>
                        </div>
                    </div>
                </div>


            </div><!-- /.blog-post -->

        </div><!-- /.blog-main -->
    </div><!-- /.row -->

</div><!-- /.container -->
{% endblock %}

shop/templates/shop/product/list.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }} {% else %} I_butich | Home {% endif %}
{% endblock %}

{% block content %}
<section id="slider">
    <!--slider-->
    <div class="container">
        <!-- <div id="ashaki" class="carouselslide" data-ride="carousel">
            <!-- indicators -->
        <!-- <ul class="carousel-indicators">
                <li data-target="#ashaki" data-slide-to="0" class="active"></li>
                <li data-target="#ashaki" data-slide-to="1" class="active"></li>
                <li data-target="#ashaki" data-slide-to="2" class="active"></li>
            </ul> -->
        <!-- The slideshow -->
        <!-- <div class="carousel-inner">
                <div class="carousel-item active">
                    <div class="carousel-caption">
                        <h1>Welcome to Ashaki Grill</h1>
                        <p class="text-center">Fresh Food, Made Real Good!!!</p>

                    </div>
                </div>
                <div class="carousel-item active">
                    <h1>Place your order</h1>
                </div>
                <div class="carousel-item active">
                    <h1>Book Reservation</h1>
                </div>
            </div> -->
        <!-- left and right controls -->
        <!-- <a href="#ashaki" class="carousel-control-prev" data-slide="prev">
                <span class="carousel-prev-icon"></span>
            </a>
            <a href="#ashaki" class="carousel-control-next" data-slide="next">
                <span class="carousel-next-icon"></span>
            </a>

        </div> -->

        <!-- <marquee behavior="rotate" direction="left" style="color:orangered; font-style:italic">
            <h2 class="text-center">Fresh Food, Made Real
                Good!!!</h2>
            <p class="text-center"> Place Your Order and GET it prepared in advance or Reserve a table
                in advance.</p>
            <h2 class="text-center">OR</h2>
            <p class="text-center">Place Your Order and let it be delivered to You wherever you are
            </p>


        </marquee> -->
    </div>
</section>
<!--/slider-->
<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="sidebar-module list-group">
                    <h2 class="title text-center">Categories</h2>
                    <ol class="list-unstyled">
                        <li {% if not category %} class="active" {% endif %}><a href="{% url 'shop:product_list' %}"
                                style=" color: #FE980F; text-transform: uppercase;">
                                <h2>All</h2>
                            </a></li>
                        {% for c in categories %}

                        <li {% if category.slug == c.slug %} class="active" {% endif %}>
                            <a href="{{ c.get_absolute_url }}" style=" color: #FE980F; text-transform: uppercase;">
                                <h2>{{ c.name }}</h2>
                            </a>
                        </li>
                        {% endfor %}
                    </ol>
                </div>
            </div>

            <div class="col-sm-9 padding-right">
                <div class="features_items">
                    <!--menu_items-->
                    <h2 class="title text-center">Our Menu</h2>

                    {% for product in products %}

                    <div class="col-sm-4">
                        <div class="product-image-wrapper">
                            <div class="single-products">
                                <div class="productinfo text-center">
                                    <a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}"
                                            alt="{{ product.name }}" class="img-fluid" /></a>
                                    <h2>Kshs. {{ product.price }}</h2>
                                    <p><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></p>

                                </div>
                            </div>
                            <div class="text-center">
                                <a href="{{ product.get_absolute_url }}" class="btn btn-default add-to-cart ">Place
                                    Order</a>
                            </div>
                        </div>
                    </div>

                    {% endfor %}

                </div>
                <!--menu_items-->

            </div>
        </div>
    </div>
</section>
{% endblock %}